name: ${name}
version: ${version}
main: ${mainClass}
author: ${author}
website: ${url}
softdepend: [VanishNoPacket]

commands:
    marcoradar:
        description: Displays list of player locations
        aliases: [marco,listloc]